version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: film_postgres
    environment:
      POSTGRES_DB: filmsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: film_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - rest-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: film_web
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:admin@film_postgres:5432/filmsdb?sslmode=disable
      - REDIS_URL=film_redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rest-network

  nginx:
    image: nginx:alpine
    container_name: film_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      web:
        condition: service_started
    networks:
      - rest-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - rest-network

  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0
    volumes:
      - ./grafana/grafana.yml:/etc/grafana/provisioning/datasource/datasource.yml
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - rest-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  rest-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  grafana_data:
