global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'film-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'film-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['film_web:8080']
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):8080'
        target_label: instance
        replacement: '$1'

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'film_postgres:9187' ]
        labels:
          service: 'postgres'

  - job_name: 'redis'
    static_configs:
      - targets: ['film_redis:9121']
        labels:
          service: 'redis'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']