DROP TABLE IF EXISTS films;

CREATE TABLE films(
    id SERIAL PRIMARY KEY,
    nameFilm VARCHAR(255) NOT NULL,
    duration INTEGER NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
